use_frameworks!

platform :ios, '10.0'

target 'Mediator_Example' do
  pod 'Mediator', :path => '../'

  target 'Mediator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
